apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}
  labels:
    cloud: 'AWS'
    region: {{ .Values.region }}
    vendor: OpenShift
spec:
  baseDomain: rawagner-op.link
  clusterName: {{ .Release.Namespace }}-{{ .Release.Name }}
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  platform:
    aws:
      # has to exist on cluster
      credentialsSecretRef:
        name: aws-creds
      region: {{ .Values.region }}
  provisioning:
    installConfigSecretRef:
      name: {{ .Release.Namespace }}-{{ .Release.Name }}-config
    # has to exist on cluster
    sshPrivateKeySecretRef:
      name: aws-ssh-private-key
    imageSetRef:
      name: img4.11.28-x86-64-appsub
  # has to exist on cluster
  pullSecretRef:
    name: pullsecret-cluster